version: "3"
services:
  springboot-app:
    container_name: swp-app-be
    restart: always
    image: springboot-app
    build: .
    ports:
      - 8080:8080

    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: swp-mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: swpGR1database
      MYSQL_ROOT_PASSWORD: root